import { useCallback, useEffect, useState } from 'react'
import {
  ApiError, assignCamera, getCameras, getPhoneLink, rescanCameras, swapCameras,
  type CameraRole, type CamerasInfo, type PhoneLink,
} from '../api.ts'
import { useApp } from './AppContext.tsx'

const STATE_TEXT: Record<string, [string, string]> = {
  live: ['Live', 'live'],
  waiting: ['Waiting for your phone', ''],
  unavailable: ['Not sending video. Close other apps using it, then press Rescan.', 'bad'],
  none: ['Off', ''],
}

const SLOTS: { role: CameraRole; title: string; hint: string }[] = [
  { role: 'front', title: 'Front camera', hint: 'faces you: eyes, head tilt, shoulders' },
  { role: 'side', title: 'Side camera', hint: 'from your side: neck and back angle' },
]

/** Camera slot pickers and the phone-as-camera link. Polls the backend while the Record tab is open. */
export default function CameraSetup({ active }: { active: boolean }) {
  const { showToast } = useApp()
  const [cams, setCams] = useState<CamerasInfo | null>(null)
  const [phone, setPhone] = useState<PhoneLink | null>(null)
  const [phoneOffline, setPhoneOffline] = useState(false)
  const [busy, setBusy] = useState<'swap' | 'rescan' | null>(null)

  // Camera calls hand back the current state even when a change fails.
  const change = useCallback(async (request: () => Promise<CamerasInfo>, failTitle: string) => {
    try {
      setCams(await request())
    } catch (err) {
      const data = err instanceof ApiError ? err.data as CamerasInfo : null
      if (data?.assignment) setCams(data)
      if (failTitle) showToast(failTitle, (err as Error).message)
    }
  }, [showToast])

  const loadPhone = useCallback(async (newCode: boolean) => {
    try {
      setPhone(await getPhoneLink(newCode))
      setPhoneOffline(false)
    } catch {
      setPhoneOffline(true)
    }
  }, [])

  useEffect(() => {
    if (!active) return
    // State is only set after the request resolves, so this doesn't cascade renders.
    // eslint-disable-next-line react/set-state-in-effect
    change(getCameras, '') // offline: the feed placeholders already say so
    loadPhone(false)
    const id = setInterval(() => change(getCameras, ''), 2000)
    return () => clearInterval(id)
  }, [active, change, loadPhone])

  async function runButton(kind: 'swap' | 'rescan') {
    setBusy(kind)
    await change(kind === 'swap' ? swapCameras : rescanCameras, kind === 'swap' ? 'Swap failed' : 'Rescan failed')
    setBusy(null)
  }

  const sources = cams?.sources ?? []
  const phoneRole = cams?.assignment?.front === 'phone' ? 'front' : cams?.assignment?.side === 'phone' ? 'side' : null
  const alternates = phone?.alternates ?? []

  return (
    <div className="card r-b cam-setup">
      <div className="threshold-panel-head">
        <span className="threshold-panel-title">Cameras</span>
        <div className="cam-setup-actions">
          <button className="threshold-test-btn" type="button" disabled={busy != null} onClick={() => runButton('swap')}>Swap</button>
          <button className="threshold-test-btn" type="button" disabled={busy != null} onClick={() => runButton('rescan')}>
            {busy === 'rescan' ? 'Scanning…' : 'Rescan'}
          </button>
        </div>
      </div>
      <div className="cam-setup-grid">
        {SLOTS.map(({ role, title, hint }) => {
          const [text, cls] = STATE_TEXT[cams?.status?.[role] ?? 'none'] ?? STATE_TEXT.none
          return (
            <label className="cam-slot" key={role}>
              <span className="cam-slot-label">{title} <em>{hint}</em></span>
              <select
                value={cams?.assignment?.[role] ?? ''}
                onChange={e => {
                  const value = e.target.value || null
                  e.target.blur()
                  change(() => assignCamera(role, value), 'Camera change failed')
                }}
              >
                {cams?.assignment && sources.map(s => (
                  <option key={s.id} value={s.id}>{s.id === 'phone' ? 'Phone (scan the QR code)' : s.label}</option>
                ))}
                {cams?.assignment && <option value="">None</option>}
              </select>
              <span className={cls ? `cam-slot-state ${cls}` : 'cam-slot-state'}>{cams?.assignment ? text : ''}</span>
            </label>
          )
        })}
      </div>

      <div className="phone-link">
        {phoneOffline ? (
          <div className="phone-qr" aria-label="QR code to open the phone camera page">Couldn't reach the BackTrack backend.</div>
        ) : phone?.error ? (
          <div className="phone-qr" aria-label="QR code to open the phone camera page">{phone.error}</div>
        ) : (
          // The SVG is generated by the backend's QR library.
          <div className="phone-qr" aria-label="QR code to open the phone camera page" dangerouslySetInnerHTML={{ __html: phone?.url && phone.qr_svg ? phone.qr_svg : '' }} />
        )}
        <div className="phone-steps">
          <div className="phone-steps-title">Use your phone as a camera</div>
          <ol>
            <li>Connect your phone to the same Wi-Fi as this computer.</li>
            <li>Scan this code with your phone's camera.</li>
            <li>Your phone will warn that the connection isn't private. That's expected: the link stays on your Wi-Fi. Tap <b>Show Details → visit this website</b> (iPhone) or <b>Advanced → Proceed</b> (Android). You only do this once.</li>
            <li>Tap <b>Start camera</b> and allow camera access. Stand the phone to your side at about shoulder height.</li>
          </ol>
          <div className="phone-url-row">Or type this address: <code>{phone ? phone.url || '—' : 'loading…'}</code></div>
          <div className="phone-status-row">
            <span className={cams?.phone_connected ? 'cam-status' : 'cam-status offline'}>
              <span className="dot"></span>
              {!cams?.phone_connected ? 'No phone yet'
                : phoneRole ? `Phone connected: used as the ${phoneRole} camera`
                : 'Phone connected but unused. Pick Phone in a slot above.'}
            </span>
            <button className="threshold-test-btn" type="button" onClick={() => loadPhone(true)}>New code</button>
          </div>
          <details className="phone-help">
            <summary>Phone can't connect?</summary>
            <ul>
              <li><b>Firewall:</b> the first time BackTrack runs, Windows or macOS asks whether Python may accept connections. Allow it on private networks. On Linux, open port 5051 (e.g. <code>sudo ufw allow 5051/tcp</code>).</li>
              <li><b>School, work or guest Wi-Fi</b> often stops devices from reaching each other. Turn on your phone's hotspot, connect this computer to it, then press <b>New code</b>.</li>
              <li><b>Wrong network address:</b> if this computer has several network adapters, try one of these instead: <span>{!phone ? 'none' : alternates.length ? alternates.join('  ·  ') : 'none found'}</span></li>
            </ul>
          </details>
        </div>
      </div>
    </div>
  )
}
